97 4 1
# no mild severe moderate
no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	no	mild	mild	mild	severe	severe	severe	mild	severe	mild	severe	mild	mild	severe	mild	mild	mild	mild	mild	mild	mild	mild	mild	moderate	mild	moderate	moderate	mild	mild	mild	moderate	mild	severe	mild	mild	severe	moderate	mild	mild	moderate	mild	severe	mild	mild	moderate	moderate	moderate	severe	mild	mild	severe	severe	severe	moderate	mild	moderate	severe	mild	mild	moderate	moderate	severe	mild
